### ISSUE TITLE
export default and standalone

### ISSUE THREAD

**Issue by mohsen1** [TypeStrong/tsify#105]
What should I do if I use `export default foo` syntax in TypeScript and want to have `foo` exported as standalone object?

According to https://github.com/Microsoft/TypeScript/issues/2719 there is a bit of conflict on what `export default foo` should do in TypeScript but Browserify has the concept of `standalone` so it can get mapped to the standalone export.

Foe example if my module is this:

```typescript
export default function add(a: number, b: number): number { return a + b; }
```

and I use tsify like this:

```
browserify -p [tsify] --standalone add index.ts 
```

I'm expecting `add` exported to global `window` for browsers.

**Comment by cartant** [comment]
I'm answering old question this so that I can close it. It's related to another issue on which I've recently been corresponding and I've only just noticed it.

If you have **add.ts** with this content:

    export default function add(a: number, b: number): number { return a + b; }

this command:

    browserify -p [tsify] --standalone add add.ts

will export a bundle with a global `add` object with a `default` property set to the function. That is, you'd need call the function like this:

    add.default(1, 2);

To change things so that the `add` global is the function itself by using a JS file to `require` the TS file. If **index.js** has this content:

    module.exports = require("./add").default;

this command:

    browserify -p [tsify] --standalone add index.js
will export a bundle with a global `add` function. That is, you'd be able to call the function like this:

    add(1, 2);
