### ISSUE TITLE
Question: How to transform typescript before tsify compiles it?

### ISSUE THREAD

**Issue by ElsewhereGames** [TypeStrong/tsify#113]
I am trying to apply a transform to all files before passing it along to this plugin, but the transforms are apparently ignored by tsify. I am thinking I may be doing something incorrectly in setting up my browserify workflow?

See my example here: http://stackoverflow.com/questions/35301615/tsify-ignores-transforms-during-browserify

**Comment by smrq** [comment]
This is unfortunately impossible because of architectural limitations.  tsify has to load files from disk because it pulls in extra files according to module resolution semantics.  Even if it's possible to pass those extra files through the pre-tsify transformation pipeline (which I'm thinking is unlikely), it would be disastrously unperformant.  You have to write your transformed files to disk before pulling them in to Browserify, unfortunately :/

**Comment by ElsewhereGames** [comment]
I have since switched to webpack, which allowed me to do the transformation as desired.
