### ISSUE TITLE
grunt-browserify halts on first error

### ISSUE THREAD

**Issue by laurence-myers** [TypeStrong/tsify#121]
Using grunt-browserify only displays the first TS error. Any way to fix this?

Presumably, the task needs to register an error event handler to log the errors, but I can't find how to configure this from Grunt.

Or, is there another way to call browserify from Grunt?

(Maybe related to #43?)

**Comment by smrq** [comment]
Yes, same issue, I'm sure.  `grunt-browserify` would need to be updated to catch errors thrown from Browserify instead of dropping them on the floor.

You could probably use the `postBundleCB` option to handle them yourself.  Try something like:

```
postBundleCB: function (err, src, next) {
    console.error(err);
    next(null, src);
}
```

I haven't used Grunt in several years so I have no idea if that's correct, but it's a potential starting point.

**Comment by laurence-myers** [comment]
Thanks for looking into this! :+1: However, I ended up using webpack and ts-loader. Feel free to close this issue.
