### ISSUE TITLE
Cannot import a .ts file under "node_modules"

### ISSUE THREAD

**Issue by changsi-an** [TypeStrong/tsify#134]
Please see the test project: [ts_exp.zip](https://github.com/TypeStrong/tsify/files/229031/ts_exp.zip)

"a.ts"
```
import "./node_modules/b"
```

"node_modules/b.ts"
```
export var aaa = 1;
```

As long as b.ts is under "node_modules", the following command will fail:
```
browserify a.ts -p [tsify] > bundle.js
```
The error is 
```
export var aaa = 1;
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

In the meanwhile, tsc compiler works without a problem
```
tsc a.ts --module commonjs
```

As long as `b.ts` is put to a location other than "node_modules" say "n_modules" (change a.ts to reference that place of course). The command (`browserify`) succeeds without a problem.

This essentially blocks the usage of non-relative module imports, say 
```
import "b"
```
when the import path does not start with "./" or "../", it's non-relative, and will look up under "node_modules" instead. (The [node style](https://www.typescriptlang.org/docs/handbook/module-resolution.html) look up way).

**Comment by changsi-an** [comment]
Any work around please?

**Comment by Avol-V** [comment]
As I know, if you want to use non-relative import, you should put your "b" module as `node_modules/b/index.ts`.

**Comment by justindujardin** [comment]
I'm having a similar problem. I need to fix this to continue with my work, are there any suggestions? I'd be willing to put together a PR.

**Comment by changsi-an** [comment]
@justindujardin May I see your PR please? I need this to unblock my work too.

**Comment by smrq** [comment]
This is a consequence of Browserify refusing to apply transforms to `node_modules`, which is by design.  You can declare a transform as `global`, which may or may not have horrible side-effects if you are pulling in any *other* `node_modules`, but I don't think there is presently a way to specify that `tsify`'s transform should be global.  I'll take a quick look.

**Comment by justindujardin** [comment]
@smrq I'm currently trying to specify the transform in the package that I would like to use:

```json
{
  ...
  "browserify": {
    "transform": [
      [
        "tsify"
      ]
    ]
  }
}
```

  It looks like this approach is the "right" way to handle this. Tsify does not work as expected with this setup as the index.js file is given a string argument instead of an instance of Browserify.  

I'm trying to modify tsify to support this kind of usage, but having mixed results so far.  I'll report back if I come across something workable.

Luckily this approach will work for me because I control the package.json of the library I'm trying to consume, but I'm not sure about how well it will work for third party stuff.

**Comment by smrq** [comment]
@justindujardin Yes, that would be the "right" way for a transform; however, the transform is only a small part of `tsify`'s inner workings.  `tsify` is a *plugin*, which operates differently; I don't think you can configure plugins as part of the `browser` field in `package.json`, unfortunately.

**Comment by smrq** [comment]
Okay, 0.15.3 supports the `global` option which will apply the transform to all files, whether in node_modules or otherwise.  There are more implications to this flag, so I would recommend carefully reading the Browserify docs to see if it's a good fit for your situation.

**Comment by justindujardin** [comment]
@smrq it seems like `tsify` (or more specifically `browserify`) is not well suited to consuming third party modules that include typescript in them. I will try to use webpack and see if the results are any better.
