### ISSUE TITLE
tsify is always trying to compile browserify tsx example file and failing.

### ISSUE THREAD

**Issue by Mimieam** [TypeStrong/tsify#167]
Hello, 
everytime i try to compile with tsify  ( as per [this doc](https://www.typescriptlang.org/docs/handbook/integrating-with-build-tools.html), Some HelloWorld.tsx tries to get transpiled and I get this error. 

```
$ browserify src/main.ts -p [ tsify --noImplicitAny ] > bundle.js
TypeScript error: node_modules/bs-recipes/recipes/webpack.typescript.react/src/components/HelloWorld.tsx(12,13): Error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
```

adding the JSX flag doesn't help ( i get more random errors from tsx files)

here is my main.ts  :

```
import { Hi } from "./greet";

 function showHello(divName: string, name: string) {
     const elt = document.getElementById(divName);
     elt.innerText = hi(name);
 }
 showHello("greeting", "TypeScript");
```

What am I doing wrong here ?
PS ( this compiled and run just fine with tsc)

**Comment by cartant** [comment]
You are receiving the error because the content of your `node_modules` directory is being included in the TypeScript compilation.

You need to ensure that your `tsconfig.json` contains either an `exclude` or `files` setting (if `files` is specified, `exclude` is ignored). That is, it should contain either this:

    {
        "compilerOptions": { ... },
        "exclude": ["node_modules"]
    }

or this:

    {
        "compilerOptions": { ... },
        "files": ["main.ts"]
    }

If neither is specified, TypeScript will look for files in all subdirectories.

Your `tsc` compilation likely works because you are specifying `main.ts` on the command line - a circumstance in which TypeScript doesn't look for additional files.
