### ISSUE TITLE
Support for tsc --p option? (path to project)

### ISSUE THREAD

**Issue by spacejack** [TypeStrong/tsify#168]
I'd like to be able to supply the path to the tsconfig.json file, but tsify doesn't seem to pass this through to tsc.

Eg:

    browserify src/main.ts -p [ tsify --p src ] -o public/js/app.js

So it won't pick up any of the options in tsconfig.json, meaning I have to re-add them to the command line. This gets especially bad when you have a lot of typings files as you can't include them with a wildcard. Eg:

    browserify src/main.ts src/typings/lib1/lib1.d.ts src/typings/lib2/lib2.d.ts src/typings/lib3/lib3.d.ts -p [ tsify --noImplicitAny --noImplicitReturns --suppressImplicitAnyIndexErrors ] -o public/js/app.js

Is there a way to set the path to tsconfig.json?

**Comment by cartant** [comment]
Try something like this:

    browserify src/main.ts -p [ tsify --project some/path/tsconfig.json ] -o public/js/app.js

**Comment by spacejack** [comment]
Oh that's great! That seems to be working, thank you!

**Comment by basarat** [comment]
Documented by @cartant Thanks again ! 👍 🌹

**Comment by cartant** [comment]
@basarat Actually, it seems that I've missed the [author's intentions](https://github.com/TypeStrong/tsify/issues/142#issuecomment-220400186) re: `tsc` options:

> You can point to a different tsconfig.json with the --project another-tsconfig.json option. (This is not called out explicitly in the README because it's a feature of tsc.)

I'll submit another PR later to tidy up the `README.md`, as `--project` is not an 'extra option'; its a `tsc` option that's supported by `tsify`. Also, I think I'll add support for the `tsc` option short names - like `-p`. If `tsify` is going to behave like `tsc` option-wise, I think it should support the short names. If it had, this issue would not have arisen.

**Comment by cartant** [comment]
@basarat Unfortunately, my change to expand the short-name, command-line options resulted in the target defaulting to `ES3`, so I'm going to have to make another release - with some code that's somewhat more robust.

It's a little embarrassing, that the first release for which I've been responsible is broken. Clearly, I'll have to have a closer look at the testing environment the author has set up, so that I can add some tests that cover additions like the one I've just made.
