### ISSUE TITLE
Typescript error 

### ISSUE THREAD

**Issue by JamiesonWarner** [TypeStrong/tsify#177]
I'm running into errors when I try to use tsify version 0.14.8.

```
$ browserify --version
13.1.0
```
```
$ browserify . -p [ tsify --noImplicitAny ] 
TypeError: Cannot read property 'debug' of undefined
    at parseOptions (/home/jamie/app/node_modules/p4wn/node_modules/tsify/lib/Tsifier.js:66:41)
    at new Tsifier (/home/jamie/app/node_modules/p4wn/node_modules/tsify/lib/Tsifier.js:92:15)
    at tsify (/home/jamie/app/node_modules/p4wn/node_modules/tsify/index.js:12:16)
    at nr (/usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:298:23)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:44:21
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:187:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:153:39
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:93:22)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:24:18
    at FSReqWrap.oncomplete (fs.js:82:15)

```

**Comment by cartant** [comment]
Thanks for the error report.

I would really like to get this solved. It seems related to #157. And I'm not if it's an error in `tsify` or an error in Browserify - it's the options that `tsify` receives from Browserify that are `undefined`. And I'm struggling to see how that can happen. (And I don't want to simply set the options to an empty object if `undefined` is received.)

Are you able to reproduce this with a single TS file in an otherwise empty directory? Perhaps with an  accompanying `tsconfig.json`? Would you be able to provide me with that?

In #157, I thought it could have been an older, globally installed version of Browserify, but I didn't receive any additional information regarding the issue. According to your report, you're using the same version of Browserify as I am. I would dearly like to reproduce the error here so that it can be fixed properly.

**Comment by JamiesonWarner** [comment]
Thanks for the support!

Here's a GH link: https://github.com/JamiesonWarner/tsify-example

Steps to repro:

1. `git clone git@github.com:JamiesonWarner/tsify-example.git && cd tsify-example`
2. `rm -rf node_modules && npm install # why not`
3. `browserify . -p [ tsify --noImplicitAny ] `

**Comment by cartant** [comment]
Cool. Thanks. I'll check it out later. Hopefully, I'll be able to reproduce it.

**Comment by JamiesonWarner** [comment]
It's this code in package.json that causes the problem, like in the issue you linked:
```
  "browserify": {
    "transform": [
      "tsify"
    ]
  },
```

**Comment by cartant** [comment]
Yep. That'd do it. `tsify` is a plugin, not a transform.

Typically, you'd use the `browserify/transform` configuration in `package.json` to apply a transform to a package when it's consumed via `node_modules`. `tsify` is a plugin, so that's not possible. If you need to use `tsify` to consume TypeScript from within `node_modules`, you'll need to use `tsify`'s `global` option.

**Comment by cartant** [comment]
Thanks for the repo link. I'll add test to catch `tsify`-as-transformer configurations and will throw a more descriptive error.

I noticed that you don't have a `tsconfig.json` in your repo. Without one, the performance is pretty woeful, as TypeScript will go digging through everything under `node_modules`. At some stage, I'll add some notes/guidelines. I find it best to reference only the `typings/index.d.ts` (if you use typings, that is) in the `tsconfig.json` and put the `.ts` entry points into the browserify configuration.

If you have no `tsconfig.json` or have one with neither `excludes` nor `files` configurations, TypeScript will go nuts; digging into `node_modules`. It'll work, but it'll be slow.

**Comment by cartant** [comment]
Sorry. I see that there is a `tsconfig.json` in your repo, it just has neither an `excludes` nor a `files` in it. (I should pay more attention.)

**Comment by JamiesonWarner** [comment]
So are `tsify`-as-transformer configurations not supported? What work needs to be done to be able to support them?

**Comment by cartant** [comment]
@JamiesonWarner

> So are `tsify`-as-transformer configurations not supported? What work needs to be done to be able to support them?

They cannot be supported, as `tsify` is a plugin. [Why a plugin?](https://github.com/TypeStrong/tsify#why-a-plugin)
