### ISSUE TITLE
Diagnosing problems is difficult without errors or logging

### ISSUE THREAD

**Issue by cartant** [TypeStrong/tsify#187]
There is a [question](http://stackoverflow.com/q/39090180/6680611) on StackOverflow asking how to diagnose problems with tsify. It's likely that this is related to tsify [emitting empty content](https://github.com/TypeStrong/tsify/blob/v1.0.3/lib/Tsifier.js#L298-L299) upon a repeated cache miss.

With the recent refactoring, repeated misses should be less likely - as case no longer matters, etc. - but I think it would be better if an error were emitted to Browserify.

Until a change is made and an error is emitted, some useful diagnostic information could be gathered by patching `node_modules/tsify/lib/Tsifier.js` to include some logging for repeated cache misses:

    Tsifier.prototype.getCompiledFile = function (inputFile, alreadyMissedCache) {
        ...
        if (!output) {
            if (alreadyMissedCache) {
                console.log('No compiled file for ' + inputFile);
                return;
            }
            ...

**Comment by jsmarsch** [comment]
I have encountered this problem as well (my SO post: http://stackoverflow.com/questions/39090180/how-to-get-build-error-messages-from-browserify.

When something goes wrong, you get no diagnostics at all, just missing content from browserify's output  js file, and your app stops working.  It failed recently on a dev machine, and really, all we could do was to guess.  

I think you are correct that tsify emitted no content as a result of the error -- there was nearly zero content in the concatenated output file that browserify emitted.  It seems reasonable that occurred because tsify did not pass any content along the pipeline.

In our case, a file wasn't really missing.  Instead, a developer had changed the case of a file name and checked that in to git.  (we are running on windows, so case-sensitive git with case-preserving NTFS -- we run with core.ignorecase=true)  Through trial and error, we figured out which file, and then we resorted to renaming it (which cleared the problem).  

I agree that integration with browserify  error reporting, would be best, and that at the very least, some basic logging would be extremely valuable.  If we had a known which file was causing the problem, it would have cut hours out of the effort it took to fix the problem.

In your post above, are you suggesting that we could temporarily patch that file on our builds?  Though I generally avoid that, I would have happily done it to get past the problem we were having!  If we were to do something like that, how would we make that work with NPM?  What I mean is that we use NPM as our package manager, so we don't check our vendor scripts into Git.  Instead, we do an NPM install.  Is there a way that we could patch that section of code, and still have it propagate correctly to developer machines?  (I suppose that if we check in the ./node_modules/tsify folder, then it would always be present and not be overwritten by NPM install).  

Is there a way that we could monkey-patch it, so that we don't have to alter the source?

**Comment by cartant** [comment]
The patch I was suggesting would have been for diagnostic purposes. And, yes, patching an NPM-managed file would not have been a satisfactory solution.

Fortunately, some refactoring that I did will have fixed the case-related problem that you have encountered. [This PR](https://github.com/TypeStrong/tsify/pull/171) fixed a number of outstanding bugs. I have not yet rolled out a release; I wanted to spend some time using the refactored `tsify` in anger, so to speak, as it was a significant refactoring. However, I am now confident that it's sound and will make a new release in the next few days - I would like to make the additional change that sees the repeated-cache-miss errors emitted to Browserify.

In the interim, if you wish to use a version of `tsify` that does not have the bug that caused your problem, you could use the current master in your `package.json`, 

    {
        ...
        "devDependencies": {
            ...
            "tsify": "TypeStrong/tsify.git#52a2033c7b65c206014b47268f002b085683ddcf",
            ...
        },
        ...
    }

**Comment by jsmarsch** [comment]
Sounds good.  I will watch for the release, and good to know about the patch option for getting error messages when something goes wrong.  Good luck on the repeated cache miss errors bug -- error reporting on this type of issue will be a good thing to have.

**Comment by cartant** [comment]
No worries. I'll post an answer to your SO question as soon as the release is done.

**Comment by cartant** [comment]
@jsmarsch I've released version 1.0.4 of `tsify`. It includes numerous bug fixes and the case-related issue that you experienced should no longer occur. Additionally, the internal errors that previously went unreported should now be emitted to Browserify.

**Comment by jsmarsch** [comment]
Great!  Thank you!
