### ISSUE TITLE
Compilation fails with tsify but succeeds with tsc

### ISSUE THREAD

**Issue by danielepolencic** [TypeStrong/tsify#204]
This is a very weird one:

the following valid typescript file:

```typescript
declare var require: any
const bla = require('phantomjs-prebuilt');
```

works fine when I run `tsc index.ts`.

When I run `browserify index.ts -p tsify -o ./bundle.js` I get the following error:

```bash
~/S/test ❯❯❯ browserify index.ts -p tsify -o ./bundle.js
TypeScript error: ../../../../Users/pole/Sites/test/node_modules/popsicle-retry/dist/index.d.ts(2,50): Error TS2307: Cannot find module 'popsicle'.
```

I recreated the issue in this repo: https://github.com/danielepolencic/tsify-error

It seems somehow related to `typings` (that's where the dependency on popsicle is coming from).

Originally I thought the issue was with `phantomjs-prebuilt`, but the same error can be recreated using `request` module.

```typescript
declare var require: any
const bla = require('request');
```

returns:

```bash
TypeScript error: ../../../../Users/pole/Sites/test/node_modules/popsicle-retry/dist/index.d.ts(2,50): Error TS2307: Cannot find module 'popsicle'.
```

**Comment by cartant** [comment]
The problem can be solved by adding an empty `files` setting to your `tsconfig.json`:

    {
      ...
      "files": []
    }

`tsify` will add any entry files specified in your `browserify` command.

This happens because `tsify` is still using an old version of `tsconfig` to parse the `tsconfig.json` file and - in the absence of an `exclude` or `files` setting - that module is searching through `node_modules` for `.ts` files. Basically, it's behaving in the same manner as a pre-2.0 `tsc`.

Changing this is something that I've been putting off, but clearly it's something that needs to be addressed. Thanks for raising the issue.

**Comment by cartant** [comment]
Also, I noted that in your `tsconfig.json` you are targeting `es6`. Browserify does not support ES modules, so if you target `es6`, you will need to use something like `babelify`. Targeting `es5` would be simpler.

**Comment by cartant** [comment]
This should be closed by https://github.com/TypeStrong/tsify/commit/6740d06c2bad70bfed9a1d69d3a53137abc932a3

**Comment by danielepolencic** [comment]
Thanks!
