### ISSUE TITLE
browserify output generates error

### ISSUE THREAD

**Issue by jkndrkn** [TypeStrong/tsify#214]
I have defined the below `HelloWorld` service in my Angular 1.X app in a file named hello-world.ts:

```
"use strict";

export default class HelloWorld {
  hello() {
    console.log("hello world");
  }
}
```

I import it using the following:

```
import HelloWorld from './hello-world';
angular.module('exac.helloWorld', []).service('HelloWorld', HelloWorld);
```

In the browser, I see the following error:

```
angular.js:13920 Error: [ng:areq] Argument 'fn' is not a function, got Object
```

Inspecting the output generated by  browserify, I see the following:

```
System.register([], function (exports_1, context_1) {
    "use strict";

    var __moduleName = context_1 && context_1.id;
    var HelloWorld;
    return {
        setters: [],
        execute: function execute() {
            HelloWorld = function () {
                function HelloWorld() {}
                HelloWorld.prototype.hello = function () {
                    console.log("hello world");
                };
                return HelloWorld;
            }();
            exports_1("default", HelloWorld);
        }
    };
});
```

My index.html contains the following relevant `<script>` blocks:

```
        <script src="../node_modules/systemjs/dist/system.js"></script>
        <script>
            SystemJS.import('js/index.js');
        </script>
```

And the relevant sections of my gulpfile are:

```
var browserifyArgs = {
  cache: {},
  basedir: 'app/source',
  entries: ['./index.js'],
  packageCache: {},
  fullPaths: false,
  // generate source maps
  debug: true,
};

var bundler = browserify(browserifyArgs)
  .plugin(tsify, {noImplicitAny: true})
  .transform('babelify', {
    presets: ['es2015'],
    extensions: ['.js', '.ts']
  })
  .transform('browserify-ngannotate');

function bundle() {
  return bundler.bundle()
    .on('error', console.log.bind(gutil, 'Browserify Error'))
    .pipe(source('index.js'))
    .pipe(buffer())
    .pipe(sourcemaps.init({
      loadMaps: true
    }))
    .pipe(sourcemaps.write('./', {
      includeContent: true,
      sourceRoot: '..'
    }))
    .pipe(gulp.dest('app/js/'));
}

gulp.task('js', bundle);
```

Is there an issue with my gulpfile config? Perhaps a missing dependency

**Comment by cartant** [comment]
Presumably, the `module` option in your `tsconfig.json` is set to `system`. I don't use SystemJS, so, unfortunately, I'm not in a position to advise.

**Comment by jkndrkn** [comment]
@cartant, thanks. `module` is set to `system`. Do you know of a way to serve TypeScript in the browser without using SystemJS?

**Comment by cartant** [comment]
You can use Browserify and tsify to create an ES5 bundle that can be served to the browser. There are examples in this repo that show the required configuration.

You can also use tsify to output ES6 modules and can use babelify to convert them to ES5. This repo also contains an example for that.

You could also use WebPack to create a bundle. There are numerous options.

It seems to me that part of your problem is your use of SystemJS - a module loader - with Browserify - a module bundler. If you are going to use SystemJS, there should be no need to use Browserify. My experience with SystemJS is limited to creating Plunkers for reporting issues with Angular 2. However, I cannot see how it would 'play nice' inside of a Browserify bundle - inside of which, Browserify uses it's own CommonJS module implementation.
