### ISSUE TITLE
tsify doesn't work with streams

### ISSUE THREAD

**Issue by semurgx** [TypeStrong/tsify#240]
```js
var browserify = require('browserify');
var tsify = require('tsify');
var fs = require('fs');

browserify()
    .add(fs.createReadStream('main.ts'))
    .plugin(tsify, { noImplicitAny: true })
    .bundle()
    .on('error', function (error) { console.error(error.toString()); })
    .pipe(process.stdout);
```

doesn't seem to work :(

**Comment by cartant** [comment]
The implementation won't work with streams because the TypeScript compiler host [reads the file contents from disk](https://github.com/TypeStrong/tsify/blob/v4.0.0/lib/Host.js#L156-L170). That is, the content received from Browserify is ignored and TypeScript reads the files from disk. The output from the TypeScript compiler host is then held in memory and the transpiled content is returned to Browserify.
