### ISSUE TITLE
Import HTML as strings

### ISSUE THREAD

**Issue by sebald** [TypeStrong/tsify#88]
It would be nice if tsify would allow the import of HTML (templates) as strings, e.g.

```javascript
import template = require('./my-template.html');
console.log(template);
```

Or is this already possible? I tried to make this work with `stringify` but got compile errors :(

**Comment by smrq** [comment]
If you want to do non-standard things with `require()` then TypeScript itself will not support them.  You can get around this by declaring a type declaration for `require` and not using the import syntax:

```
declare function require(path: string): any;

var template = require('./my-template.html');
```

Then you can use whatever transform you like.  Also consider trying brfs, since it doesn't overload the meaning of `require()`.

**Comment by basarat** [comment]
> You can get around this by declaring a type declaration for require and not using the import syntax:

alternatively (and recommended if you are also targetting node) that the user adds `node.d.ts` to the project

**Comment by sebald** [comment]
Thanks, I'll try your suggestions and will post my setup, if I get it working for future references :)
